name: Make CI

on:
  push:
    branches: [ "branchAutoPackage" ]
  pull_request:
    branches: [ "branchAutoPackage" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: ./configure
      run: ./configure
    - name: make dist
      run: make dist
    - name: make deb
      run: make deb
